### PR TITLE
Little fix on the admin panel.

### PR DESCRIPTION
**Pull request by goldenlink**
The project query was displaying the issue query instead.

### CODE REVIEW

**Comment by jhansche** [comment]
Thanks for the patch! Note that project search is not yet implemented, but I'm merging this now, to prepare for when it is.

**Comment by goldenlink** [comment]
You're welcome!

I'm impatient to have the project search. Especially that I want to link several repositories in Gerrit to one project. 
Is there a naming convention between Jira and Gerrit to implement to improve the integration? 

I looked at the code, and as I understand, the projectKey is the determinant for the project repository name. Maybe would be good to be able to choose on what param make the search? 
I'd like more to use both projectKey and projectName. Though I think a query like this project:^%s\* should do it. And get every repository as a prefix. Just would need to enforce the correct naming policy throughout my projects.

**Comment by jhansche** [comment]
Hmm, yeah the idea was for this information to show up on the Project browse page, as a new tab.  So it would be one search pattern per project.  But it is **not** a JIRA-project to Gerrit-Project mapping, which is what I think you are interpretting it as.  Instead, it's simply a search pattern (e.g., just the same as if you were to search for something in the search box in the top-right of your Gerrit site).

So, it could be something like `"message:%s-*"` so that if your project key is `FOO`, and you have 3 commits tagged with `FOO-1`, `FOO-2`, and `FOO-3`, it would list all three of those commits as being associated with the project.  Unfortunately, the faster database-driven searches like `tr:` and `topic:` do not appear to support wildcard matches, so that limits the usefulness of a per-project search (at least in our case).

If you are already using trackingids though (with the `tr:` search predicate), then you could easily add a second trackingid configuration that only matches on the project key portion of the JIRA issue.  That is, if your original trackingid config is searching for "`Issue: ([A-Z]+-[1-9][0-9*])`", then you could have a second config matching on "`Issue: ([A-Z]+)-[1-9][0-9]`", and that would then allow "tr:FOO" to return _all_ of the matching FOO-\* changes.

Am I misunderstanding your intent?  Could you give me an example of how many JIRA projects you're talking about, and how you would want those to be mapped to Gerrit repositories (let's not get terminology confused:  call Gerrit projects repositories, and JIRA projects :p) ?

**Comment by goldenlink** [comment]
Hi,

Well, I track JIRA issues in the commit message.  The thing is thqt for one JIRA project, I can have several components and several gerrit repositories. One for each component.

As for the moment I haven't find the way to set up a hook in Gerrit to guarantee that the developers submit patches with a JIRA ticket, I want at least to track the repositories associated to the project. 

So my way would be for the project 'Web Site', with JIRA code WS, if I have several projects in Gerrit, I would name them ws-dao, ws-ui, ... so that I can map on my JIRA project all the ws\* repositories. As a result, I would write project:^%s\* to make a regex to fin dthe repos.

Thx

**Pull request merged**
